---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calling-garfish-replica-calling-garfish
  labels:
    app: calling-garfish-replica
    chart: "gcloud-sqlproxy-0.6.7"
    release: "calling-garfish"
    heritage: "Tiller"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calling-garfish-replica
    spec:    
      containers:
      - name: "sqlproxy-replica"
        image: "b.gcr.io/cloudsql-docker/gce-proxy:1.11"
        imagePullPolicy: "Always"
        resources:
          limits:
          cpu: 150m
          memory: 150Mi
        requests:
          cpu: 100m
          memory: 100Mi
        command:
        - /cloud_sql_proxy
        - --dir=/cloudsql
        - -instances="our-spanner-217012":"us-central1":"second-gen-1545229203428"=tcp:0.0.0.0:3306,
        - -credential_file=/secrets/cloudsql/credentials.json
        ports:
        - name: second-gen-1545
          containerPort: 3306
        volumeMounts:
        - name: cloudsql-oauth-credentials
          mountPath: /secrets/cloudsql
        - name: cloudsql
          mountPath: /cloudsql
      volumes:
      - name: cloudsql-oauth-credentials
        secret:
          secretName: calling-garfish-gcloud-sqlproxy
            - name: cloudsql
        emptyDir: {}
      affinity: {}
      tolerations: []
      
      nodeSelector:
        cluster: primary
        

