
serviceAccountKey: ""
existingSecret: ""
existingSecretKey: ""
port: 3306
region: "region"
project: "our-spanner-217012"

instances:
  - instance: "firstdb"
    name: master
    # Optional abbreviation used to override the truncated instance name if the
    # 15 character instance name prefix is not unique for use as a port
    instanceShortName: ""
    replicasCount: 1
  - instance: "second"
    name: replica
    instanceShortName: ""
    replicasCount: 1

image:
  repo: b.gcr.io/cloudsql-docker/gce-proxy
  tag: "1.11"
  pullPolicy: IfNotPresent


rbac:
  create: false

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 150Mi
    cpu: 150m

## Node selector
nodeSelector: 
  app: back
## Tolerations
tolerations: []

## Affinity
affinity: {}

podDisruptionBudget: |
  maxUnavailable: 1

