---
serviceAccountKey: "test"
existingSecret: ""
existingSecretKey: ""
port: 3306
region: "us-central1"
project: "our-spanner-217012"

instances:
  - instance: "firstdb"
    name: master
    instanceShortName: "aa"
    replicasCount: 1
  - instance: "second-gen-1545229203428"
    name: replica
    instanceShortName: "ab"
    replicasCount: 1

image:
  repo: b.gcr.io/cloudsql-docker/gce-proxy
  tag: "1.11"
  pullPolicy: Always

rbac:
  create: false

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 150Mi
    cpu: 150m

## Node selector
nodeSelector:
  cluster: primary
## app: back

## Tolerations
tolerations: []

## Affinity
affinity: {}

podDisruptionBudget: |
  maxUnavailable: 1
