{{- $labels := include "lables_yaml" . }}
{{- $chartName := include "gcloud-sqlproxy.name" . }}
{{ $port := .Values.port }}
{{ $project := .Values.project }}
{{ $region := .Values.region }}
{{ $imagePullPolicy := .Values.image.pullPolicy }}
{{- $volumeMount := include "volumeMounts" . }}
{{- $oauthCredentials := include "oauth-credentials" . }}
{{- $rbacCreate := include "rbacSpec" . }}
{{ $nodeSelector := .Values.nodeSelector }}
{{ $affinity := .Values.affinity }}
{{ $tolerations := .Values.tolerations }}
{{ $CredFile := include "credentials-filename" . }}
{{ $image := "{{ .Values.image.repo }}:{{ .Values.image.tag }}" }}
{{ $imagePullPolicy := .Values.image.pullPolicy | quote  }}
{{ $resources := .Values.resources }}

{{- range .Values.instances }}
{{- $name :=default .name .instance | trunc 10 | trimSuffix "-" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  {{- if contains "replica" .instance }}
  name: {{ $chartName }}-replica-{{ $name }}-{{ $chartName }}
  {{- else }}
  name: {{ $chartName }}-{{ $chartName }}
  {{- end }}
  labels:
    app: "{{ $chartName }}-{{ $name }}"
spec:
  replicas: {{ .replicasCount }}
  template:
    metadata:
      labels:
        app: "{{ $chartName }}-{{ $name }}"
    spec:
{{- $rbacCreate | indent 4 }}
      containers:
      - name: sqlproxy-{{ .instance }}
        image: "{{ $image }}"
        imagePullPolicy: {{ $imagePullPolicy }}
        resources:
{{ toYaml $resources | indent 10 }}
        command:
        - /cloud_sql_proxy
        - --dir=/cloudsql
{{  $CredFile | indent 8 -}}
        - -instances= {{ $project }}:{{ $region }}:{{ .instance }}=tcp:0.0.0.0:{{ $port }}
        ports:
        - name: {{ .instanceShortName | default $name }}
          containerPort: {{ $port }}
        volumeMounts:
{{ $volumeMount | indent 8 }}
        - name: cloudsql
          mountPath: /cloudsql
      volumes:
{{  $oauthCredentials | indent 6 }}
      - name: cloudsql
        emptyDir: {}
      nodeSelector:
{{ toYaml $nodeSelector | indent 8 }}
      affinity:
{{ toYaml $affinity | indent 8 }}
      tolerations:
{{ toYaml $tolerations | indent 8 }}
{{- end }}
