{{- $labels := include "lables_yaml" . }}
{{- $chartName := include "gcloud-sqlproxy.name" . }}
{{- if ne (index .Values.instances 0).instance "instance" }}
{{ $port := .Values.port }}
{{ $project := .Values.project }}
{{ $region := .Values.region }}
{{ $image := printf "%s:%s" .Values.image.repo .Values.image.tag }}
{{ $imagePullPolicy := .Values.image.pullPolicy }}
{{- $imageAttributes := include "container.image" . }}
{{- $volumeMount := include "volumeMounts" . }}
{{- $containerSpec := include "container.spec" . }}
{{- $rbacCreate := include "rbacSpec" . }}
{{ $nodeSelector := .Values.nodeSelector -}}

{{- range .Values.instances }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  {{- if eq .name "master" }}
  name: {{ $chartName }}-{{ $chartName }}
  {{- else }}
  name: {{ $chartName }}-{{ .name }}-{{ $chartName }}
  {{- end }}
  labels:
    app: {{ $chartName }}-{{ .name }}
{{ $labels | indent 4 }}
spec:
  replicas: {{ .replicasCount }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}-{{ .name }}
    spec:
{{ $rbacCreate | indent 4 }}
      nodeSelector:
{{ toYaml $nodeSelector | indent 8 }}
      containers:
      - name: "sqlproxy-{{ .name }}"
{{ $imageAttributes | indent 8  }}
        command:
        - /cloud_sql_proxy
        - --dir=/cloudsql
        - -instances= {{ $project }}:{{ $region }}:{{ .instance }}=tcp:0.0.0.0:{{ $port }}
        - -credential_file=/secrets/cloudsql/{{ template "credentials-filename" }}
        ports:
        - name: {{ .instanceShortName | default (.instance | trunc 15) }}
          containerPort: {{ $port }}
{{ $volumeMount | indent 8 }}
{{ $containerSpec | indent 6 }}
{{- end }}
{{- end }}
