{{- $labels := include "lables_yaml" . }}
{{- $chartName := include "sqlproxy.chart.name" . }}
{{- $releaseName := include "sqlproxy.release.name" . }}
{{ $serviceAccountKey := .Values.serviceAccountKey }}
{{- if not .Values.existingSecret -}}
{{- range .Values.instances }}
{{- $name :=default .name .instance | trunc 20 | trimSuffix "-" }}
apiVersion: v1
kind: Secret
metadata:
  {{- if contains "replica" .instance }}
  name: {{ $chartName }}-replica-{{ $releaseName }}
  {{- else }}
  name: {{ $chartName }}-{{ $releaseName }}
  {{- end }}
  labels:
    app: {{ $chartName }}-{{ $name }}
{{ $labels | indent 4 }}
type: Opaque
data:
  credentials.json: |-
    {{ $serviceAccountKey }}
{{- end }}
{{- end -}}
